[workspace]
members = ["crypto_rand_f64",
           "external",
           "protover",
           "smartlist",
           "tor_allocate",
           "tor_rust",
           "tor_util"]

[profile.release]
debug = true
panic = "abort"

